### PR TITLE
update contributors

### PR DESCRIPTION
**Pull request by Vikctar**

### CODE REVIEW

**Review by Ferencz — COMMENTED** [review]
**[Victor McDowell](https://github.com/ferencz)**

**Comment by Vikctar** [comment]
@Ferencz You are already on the list.

**Comment by Ferencz** [comment]
> @Ferencz You are already on the list.

There is a typo on the hyperlink ```https://github.com/ferecz``` please note that there is an n ```https://github.com/ferencz```

**Comment by Vikctar** [comment]
FIxed it. Thanks for pointing it out.

**Pull request merged**
